version: 1.3.0
services:
  - mysql
  - composer:
      version: 2
  - php:
      version: 8.2

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
      - setup-env:
          type: script
          script:
            - composer install --ansi
      - validate:
          type: script
          script:
            - $SOURCE_DIR/vendor/bin/blt validate:yaml -vvv
      - node-versions:
          type: script
          script:
            - nvm list
            - node --version
            - npm --version
